version: '3'
   
services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
   
  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '9292:9292'
    volumes:
      - '.:/chatbot'
      - 'box:/box'
    environment:
      - LANG=C.UTF-8

  box:
    image: busybox
    volumes:
      - box:/box
   
volumes:
  postgres:
  box: